"""
intent_engine.plugins.task_manager
====================================
TaskManagerPlugin — handles all task and project management intents.

Covers 30 intents across task lifecycle, project management,
sprint operations, search, calendar, timer, and team operations.

This plugin is the direct replacement for the removed JS INTENT_RULES
array in use-voice-action.ts.
"""

from __future__ import annotations

from typing import Any

from intent_engine.entities import EntityExtractor
from intent_engine.plugins.base import IntentDefinition, IntentPlugin


class TaskManagerPlugin(IntentPlugin):
    """All TickZen task and project management intents."""

    # ------------------------------------------------------------------
    # Plugin identity
    # ------------------------------------------------------------------

    @property
    def namespace(self) -> str:
        return "task_manager"

    # ------------------------------------------------------------------
    # Intent definitions
    # ------------------------------------------------------------------

    @property
    def intent_definitions(self) -> list[IntentDefinition]:  # type: ignore[override]
        return [
            # ── Task CRUD ─────────────────────────────────────────────────────
            {
                "name":             "CREATE_TASK",
                "verbs":            ["create", "add", "make", "new"],
                "synonyms":         ["build", "start", "open", "generate"],
                "entity_nouns":     ["task", "ticket", "issue", "item"],
                "needs_task":       True,
                "needs_project":    True,
                "needs_user":       True,
                "needs_status":     False,
                "needs_priority":   True,
                "needs_date":       True,
                "required_entities": ["title"],
            },
            {
                "name":             "DELETE_TASK",
                "verbs":            ["delete", "remove", "erase", "trash", "cancel"],
                "synonyms":         ["drop", "discard", "wipe", "clear"],
                "entity_nouns":     ["task", "ticket", "issue"],
                "needs_task":       True,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": ["title"],
            },
            {
                "name":             "UPDATE_TASK",
                "verbs":            ["update", "edit", "modify", "change"],
                "synonyms":         ["revise", "alter", "adjust", "fix"],
                "entity_nouns":     ["task", "ticket"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     True,
                "needs_priority":   True,
                "needs_date":       True,
                "required_entities": [],
            },
            {
                "name":             "ASSIGN_TASK",
                "verbs":            ["assign", "give", "delegate"],
                "synonyms":         ["allocate", "connect", "hand off", "send to"],
                "entity_nouns":     ["task", "ticket"],
                "needs_task":       True,
                "needs_project":    True,
                "needs_user":       True,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "MOVE_TASK",
                "verbs":            ["move", "shift", "transfer"],
                "synonyms":         ["relocate", "drag", "put"],
                "entity_nouns":     ["task", "ticket"],
                "needs_task":       True,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     True,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "CHANGE_STATUS",
                "verbs":            ["change status", "update status", "set status", "mark"],
                "synonyms":         ["flag", "label"],
                "entity_nouns":     ["task", "status", "ticket"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     True,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "CHANGE_PRIORITY",
                "verbs":            ["change priority", "update priority", "set priority"],
                "synonyms":         ["prioritize", "reprioritize", "escalate"],
                "entity_nouns":     ["task", "priority", "ticket"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   True,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "ARCHIVE_TASK",
                "verbs":            ["archive"],
                "synonyms":         ["hide", "shelve", "store"],
                "entity_nouns":     ["task", "ticket"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "RESTORE_TASK",
                "verbs":            ["restore", "recover", "unarchive", "reopen"],
                "synonyms":         ["bring back", "reinstate"],
                "entity_nouns":     ["task", "ticket"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "MARK_COMPLETE",
                "verbs":            ["mark", "complete", "finish", "close", "resolve"],
                "synonyms":         ["done with", "wrap up", "finalise", "finalize"],
                "entity_nouns":     ["task", "ticket", "done", "complete"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            # ── Project ───────────────────────────────────────────────────────
            {
                "name":             "CREATE_PROJECT",
                "verbs":            ["create", "add", "make", "new", "start", "build"],
                "synonyms":         ["launch", "open", "initiate", "setup", "set up",
                                     # Common Whisper ASR mishearings of "create project":
                                     "prajet", "crajet", "creat", "crate", "projekt",
                                     "prject", "projeect"],
                "entity_nouns":     ["project", "projects", "projected", "workspace"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": ["project_name"],
            },
            {
                "name":             "OPEN_PROJECT",
                "verbs":            ["open", "go to", "navigate to", "show", "view"],
                "synonyms":         ["display", "load"],
                "entity_nouns":     ["project"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            # ── Sprint ────────────────────────────────────────────────────────
            {
                "name":             "CREATE_SPRINT",
                "verbs":            ["create", "add", "make", "new"],
                "synonyms":         ["start", "plan"],
                "entity_nouns":     ["sprint", "iteration"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       True,
                "required_entities": [],
            },
            {
                "name":             "START_SPRINT",
                "verbs":            ["start", "begin", "kick off", "launch"],
                "synonyms":         ["activate", "initiate"],
                "entity_nouns":     ["sprint", "iteration"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "END_SPRINT",
                "verbs":            ["end", "close", "finish", "complete", "stop"],
                "synonyms":         ["wrap up", "finalize", "terminate"],
                "entity_nouns":     ["sprint", "iteration"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            # ── Search ────────────────────────────────────────────────────────
            {
                "name":             "SEARCH_TASK",
                "verbs":            ["search", "find", "look for", "locate", "get"],
                "synonyms":         ["fetch", "retrieve", "lookup"],
                "entity_nouns":     ["task", "ticket"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "SEARCH_PROJECT",
                "verbs":            ["search", "find", "look for", "locate", "get"],
                "synonyms":         ["fetch", "retrieve", "lookup"],
                "entity_nouns":     ["project"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            # ── Views ─────────────────────────────────────────────────────────
            {
                "name":             "LIST_TASKS",
                "verbs":            ["list", "show", "display", "get all", "view"],
                "synonyms":         ["enumerate", "print"],
                "entity_nouns":     ["tasks", "tickets", "all tasks"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     True,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "SHOW_DASHBOARD",
                "verbs":            ["show", "open", "go to", "navigate to", "view"],
                "synonyms":         ["display", "load"],
                "entity_nouns":     ["dashboard", "home", "overview"],
                "needs_task":       False,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "SHOW_CALENDAR",
                "verbs":            ["show", "open", "go to", "view"],
                "synonyms":         ["display"],
                "entity_nouns":     ["calendar", "schedule", "timeline"],
                "needs_task":       False,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "SHOW_NOTIFICATIONS",
                "verbs":            ["show", "open", "view", "check"],
                "synonyms":         ["display", "list"],
                "entity_nouns":     ["notifications", "alerts", "updates"],
                "needs_task":       False,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "SHOW_DEADLINES",
                "verbs":            ["show", "list", "get", "find", "display"],
                "synonyms":         ["check", "view"],
                "entity_nouns":     ["overdue", "delayed", "late", "deadlines", "due"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "SHOW_TEAM_MEMBERS",
                "verbs":            ["show", "list", "view", "get"],
                "synonyms":         ["display", "check"],
                "entity_nouns":     ["team", "members", "developers", "people", "teammates"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            # ── Notes ─────────────────────────────────────────────────────────
            {
                "name":             "CREATE_NOTE",
                "verbs":            ["create", "add", "make", "write", "note"],
                "synonyms":         ["jot", "record", "save"],
                "entity_nouns":     ["note", "comment", "memo"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            # ── Team ──────────────────────────────────────────────────────────
            {
                "name":             "ADD_MEMBER",
                "verbs":            ["add", "invite", "include"],
                "synonyms":         ["onboard", "bring in", "welcome"],
                "entity_nouns":     ["member", "user", "person", "developer", "teammate"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       True,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "REMOVE_MEMBER",
                "verbs":            ["remove", "kick", "exclude", "uninvite"],
                "synonyms":         ["offboard", "boot", "expel"],
                "entity_nouns":     ["member", "user", "person", "developer", "teammate"],
                "needs_task":       False,
                "needs_project":    True,
                "needs_user":       True,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            # ── Time tracking ─────────────────────────────────────────────────
            {
                "name":             "LOG_TIME",
                "verbs":            ["log", "track", "record"],
                "synonyms":         ["enter", "add"],
                "entity_nouns":     ["time", "hours", "log"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       True,
                "required_entities": [],
            },
            {
                "name":             "START_TIMER",
                "verbs":            ["start timer", "begin timer", "timer start", "time task", "track time for"],
                "synonyms":         ["run timer", "kick off timer", "begin timing"],
                "entity_nouns":     ["timer", "stopwatch", "clock", "timing"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            {
                "name":             "STOP_TIMER",
                "verbs":            ["stop timer", "pause timer", "end timer", "stop timing"],
                "synonyms":         ["halt timer", "finish timer"],
                "entity_nouns":     ["timer", "stopwatch", "clock", "timing"],
                "needs_task":       False,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       False,
                "required_entities": [],
            },
            # ── Deadline ──────────────────────────────────────────────────────
            {
                "name":             "UPDATE_DEADLINE",
                "verbs":            ["update deadline", "set deadline", "change deadline", "reschedule"],
                "synonyms":         ["move deadline", "extend deadline", "push deadline"],
                "entity_nouns":     ["deadline", "due date", "due"],
                "needs_task":       True,
                "needs_project":    False,
                "needs_user":       False,
                "needs_status":     False,
                "needs_priority":   False,
                "needs_date":       True,
                "required_entities": [],
            },
        ]

    # ------------------------------------------------------------------
    # Entity extraction
    # ------------------------------------------------------------------

    def extract_entities(self, text: str, intent_name: str) -> dict[str, Any]:
        """Delegate to shared EntityExtractor with correct hints per intent."""
        defn = next(
            (d for d in self.intent_definitions if d["name"] == intent_name),
            None,
        )
        if defn is None:
            return {}
        return EntityExtractor.extract(
            text,
            intent_name,
            needs_task     = defn["needs_task"],
            needs_project  = defn["needs_project"],
            needs_user     = defn["needs_user"],
            needs_status   = defn["needs_status"],
            needs_priority = defn["needs_priority"],
            needs_date     = defn["needs_date"],
        )
